# Generated by Django 5.0 on 2023-12-11 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tasks', '0002_delete_tipodocumento_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('dni', models.CharField(max_length=255, unique=True, verbose_name='Identificacion')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='correo electronico')),
                ('nombres', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombres')),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True, verbose_name='apellidos')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_interno', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('tipo_documento', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tasks.tipodocumento')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
